### ISSUE TITLE
create AEX proposal for the NFT standard

### ISSUE THREAD

**Issue by marc0olo** [appinesshq/ae-nft#1]
I think it would be great to have a corresponding AEX proposal for this NFT "reference implementation":
- https://github.com/aeternity/AEXs

**Comment by arjanvaneersel** [comment]
Good idea. I will take care of that. Only one thing I don't get. Why is there a jump from AEX-10 to AEX-130?

**Comment by arjanvaneersel** [comment]
[AEX proposal](https://github.com/aeternity/AEXs/issues/141) created.
