### ISSUE TITLE
Is get_uri misspelled in nft.aes?

### ISSUE THREAD

**Issue by Lfh2msn** [appinesshq/ae-nft#10]
Is **get_uri** misspelled in nft.aes?

In line 77, should **get_uri** be get_url ? (i->l or I->L)

**Comment by arjanvaneersel** [comment]
You are probably right. However this repo is outdated, because it was made before the AEX proposal for NFTs. I am currently updating everything and new examples will be available soon. I would not recommend using the examples currently in this repo.
