### ISSUE TITLE
Is this needed?

### ISSUE THREAD

**Issue by mradkov** [appinesshq/ae-nft#2]
https://github.com/appinesshq/ae-nft/blob/a101e4e5b344d71bb6ed6d129e650b0eb95ae0b9/contracts/NFT.aes#L258-L259

**Comment by arjanvaneersel** [comment]
It took me a while to get the safe transfer working, this was one of the helper functions. I can indeed remove it now, as I completely changed the implementation to a much more simplified version than it was before.

**Comment by arjanvaneersel** [comment]
Implemented with [commit 76da1be1eebcd383675ca6b43435016c91f1463d](https://github.com/appinesshq/ae-nft/commit/76da1be1eebcd383675ca6b43435016c91f1463d).
