### ISSUE TITLE
Is this return of bool actually needed?

### ISSUE THREAD

**Issue by mradkov** [appinesshq/ae-nft#3]
Is this return of bool values actually needed? Can you use `unit` where there is no intention to return any value?

https://github.com/appinesshq/ae-nft/blob/a101e4e5b344d71bb6ed6d129e650b0eb95ae0b9/contracts/NFT.aes#L90
https://github.com/appinesshq/ae-nft/blob/a101e4e5b344d71bb6ed6d129e650b0eb95ae0b9/contracts/NFT.aes#L104
https://github.com/appinesshq/ae-nft/blob/a101e4e5b344d71bb6ed6d129e650b0eb95ae0b9/contracts/NFT.aes#L136

**Comment by arjanvaneersel** [comment]
The bools were there to help me debugging during development. They will be removed indeed.

**Comment by arjanvaneersel** [comment]
Solved with [commit 64754a6a239627738d63be6e93ee592bd8c4ae28](https://github.com/appinesshq/ae-nft/commit/64754a6a239627738d63be6e93ee592bd8c4ae28).
