### ISSUE TITLE
🤔 

### ISSUE THREAD

**Issue by mradkov** [appinesshq/ae-nft#4]
https://github.com/appinesshq/ae-nft/blob/a101e4e5b344d71bb6ed6d129e650b0eb95ae0b9/contracts/NFT.aes#L7

**Comment by arjanvaneersel** [comment]
I forgot to remove this. It's the zero value address.

**Comment by arjanvaneersel** [comment]
Solved with [commit 76da1be1eebcd383675ca6b43435016c91f1463d](https://github.com/appinesshq/ae-nft/commit/76da1be1eebcd383675ca6b43435016c91f1463d).
