### ISSUE TITLE
suggestion: meta_info field

### ISSUE THREAD

**Issue by mradkov** [appinesshq/ae-nft#5]
https://github.com/appinesshq/ae-nft/blob/a101e4e5b344d71bb6ed6d129e650b0eb95ae0b9/contracts/NFT.aes#L42-L43

Can these be put in a `meta_info` field to try sticking to a more compatible NFT <> FT standard?

ref: https://github.com/mradkov/aeternity-fungible-token#meta_info

**Comment by arjanvaneersel** [comment]
I considered to do this, but eventually kept them this way and added another mechanism for metadata. I can of course implement it as you suggested if it would be better for compatibility.

**Comment by arjanvaneersel** [comment]
Implemented with [commit 76da1be1eebcd383675ca6b43435016c91f1463d](https://github.com/appinesshq/ae-nft/commit/76da1be1eebcd383675ca6b43435016c91f1463d).
