### ISSUE TITLE
suggestion: error messages (format & content)

### ISSUE THREAD

**Issue by mradkov** [appinesshq/ae-nft#6]
I know this is early reference implementation (#7 ), but .. Can you maybe provide more explanatory error messages and maybe if possible for all of them to follow a certain format? (it will be easier to handle things off-chain programmatically if so).

**Comment by arjanvaneersel** [comment]
No problem. Is there a particular recommended / idiomatic way defined for AE to communicate errors?

**Comment by arjanvaneersel** [comment]
Implemented with [commit 05e4ef914f2e8387eea59b6bc2db8f20f9b26b42](https://github.com/appinesshq/ae-nft/commit/05e4ef914f2e8387eea59b6bc2db8f20f9b26b42).
