### ISSUE TITLE
update to aeproject v4.0.0 and latest sdk

### ISSUE THREAD

**Issue by marc0olo** [appinesshq/ae-nft#9]
if you continue working on this I highly recommend to use the upcoming aeproject version. it's currently in beta and will soon be released.

- `npm i @aeternity/aeproject@4.0.0-beta.3`

migration guide:
- https://aeternity.com/aeproject/main/migration-from-3.x.x-to-4.x.x/#migration-of-old-projects

it's still beta and for consistency reasons we will probably introduce additional changes in regards to function and variable name around the sdk, see https://github.com/aeternity/aeproject/issues/402

everything related to `client` will probably be renamed to `aeSdk`

you get a lot of benefits using the latest aeproject version as it is using devmode of the aeternity node

**Comment by arjanvaneersel** [comment]
Will do!
